[build]
  publish = "."
  command = ""
  ignore = "exit 0"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disabled = true
