-- ============================================================================
-- LOUEURS (annuaire) -> fiches VITRINE dans NEXUS Location (is_rental), attribuees
-- a l'ADMIN. Categorie deduite du nom, prix « sur devis » (pas de price_per_day donc
-- aucune ligne de prix affichee), vrai telephone visible dans specs.condition.
-- Genere depuis prospection/loueurs_materiel_senegal.csv. Idempotent.
-- ============================================================================

do $$ begin
  if not exists (select 1 from public.profiles where role='admin') then
    raise exception 'Aucun compte admin (profiles.role=admin).';
  end if;
end $$;

drop table if exists _loueurs;
create temp table _loueurs(name text, category text, description text, vendor_name text, rental_specs jsonb);
insert into _loueurs values
('DALLY BEST (matériel événementiel)','Événementiel','Location — Événementiel. Contact : +221 76 941 82 40. Tarif sur devis.','DALLY BEST (matériel événementiel)','{"category": "Événementiel", "region": "Dakar", "condition": "☎ +221 76 941 82 40 · sur devis", "annonceur": "DALLY BEST (matériel événementiel)", "contact_phone": "+221 76 941 82 40", "contact_source": "toutypasse.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('NERI GROUP (location événementiel)','Événementiel','Location — Événementiel. Contact : +221 77 482 59 99. Tarif sur devis.','NERI GROUP (location événementiel)','{"category": "Événementiel", "region": "Dakar", "condition": "☎ +221 77 482 59 99 · sur devis", "annonceur": "NERI GROUP (location événementiel)", "contact_phone": "+221 77 482 59 99", "contact_source": "nerigroupinter.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('SENEDI SM Events (tentes/mobilier)','Événementiel','Location — Événementiel. Contact : senedism.com. Tarif sur devis.','SENEDI SM Events (tentes/mobilier)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "SENEDI SM Events (tentes/mobilier)", "contact_phone": null, "contact_source": "senedism.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Ayuf Holding SN (articles événementiels)','Événementiel','Location — Événementiel. Contact : ayuf.sn. Tarif sur devis.','Ayuf Holding SN (articles événementiels)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Ayuf Holding SN (articles événementiels)", "contact_phone": null, "contact_source": "ayuf.sn", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Avis Sénégal (location voiture)','Voiture','Location — Voiture. Contact : +221 33 849 77 55 · Loxea, Km 2.5 Bd du Centenaire. Tarif sur devis.','Avis Sénégal (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 849 77 55 · sur devis", "annonceur": "Avis Sénégal (location voiture)", "contact_phone": "+221 33 849 77 55", "contact_source": "avis.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('KAMA Automobile (location voiture)','Voiture','Location — Voiture. Contact : +221 78 454 79 79 · Showroom Point E. Tarif sur devis.','KAMA Automobile (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 78 454 79 79 · sur devis", "annonceur": "KAMA Automobile (location voiture)", "contact_phone": "+221 78 454 79 79", "contact_source": "kamaautomobile.sn", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Nouvelles Frontières Sénégal (location véhicule)','Voiture','Location — Voiture. Contact : +221 33 859 44 47 · Lot n°1 Mamelles Aviation. Tarif sur devis.','Nouvelles Frontières Sénégal (location véhicule)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 859 44 47 · sur devis", "annonceur": "Nouvelles Frontières Sénégal (location véhicule)", "contact_phone": "+221 33 859 44 47", "contact_source": "nfsenegal.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('SELOV - Sénégalaise de Location de Voitures','Voiture','Location — Voiture. Contact : +221 33 827 57 26 · Lotissement n°57, VDN. Tarif sur devis.','SELOV - Sénégalaise de Location de Voitures','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 827 57 26 · sur devis", "annonceur": "SELOV - Sénégalaise de Location de Voitures", "contact_phone": "+221 33 827 57 26", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Mass Location (location voiture)','Voiture','Location — Voiture. Contact : +221 33 822 04 62 · AIBD Terminal principal. Tarif sur devis.','Mass Location (location voiture)','{"category": "Voiture", "region": "Thiès", "condition": "☎ +221 33 822 04 62 · sur devis", "annonceur": "Mass Location (location voiture)", "contact_phone": "+221 33 822 04 62", "contact_source": "dakaraeroport.com", "ville": "Diass", "is_vitrine": true}'::jsonb),
('National Location de Voitures','Voiture','Location — Voiture. Contact : senegal-online.com · Km 2.5 Bd du Centenaire. Tarif sur devis.','National Location de Voitures','{"category": "Voiture", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "National Location de Voitures", "contact_phone": null, "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('2JR Location de Voitures','Voiture','Location — Voiture. Contact : +221 33 821 98 56 · Rue Moussé Diop Plateau. Tarif sur devis.','2JR Location de Voitures','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 821 98 56 · sur devis", "annonceur": "2JR Location de Voitures", "contact_phone": "+221 33 821 98 56", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('ADA Location de Véhicules','Voiture','Location — Voiture. Contact : +221 33 869 25 26 · Mermoz. Tarif sur devis.','ADA Location de Véhicules','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 869 25 26 · sur devis", "annonceur": "ADA Location de Véhicules", "contact_phone": "+221 33 869 25 26", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Afrique Location de Voitures','Voiture','Location — Voiture. Contact : +221 33 823 88 01 · Rue Amadou Assane Ndoye Plateau. Tarif sur devis.','Afrique Location de Voitures','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 823 88 01 · sur devis", "annonceur": "Afrique Location de Voitures", "contact_phone": "+221 33 823 88 01", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Autoland Sénégal (location voiture)','Voiture','Location — Voiture. Contact : +221 33 864 17 17 · Avenue Bourguiba. Tarif sur devis.','Autoland Sénégal (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 864 17 17 · sur devis", "annonceur": "Autoland Sénégal (location voiture)", "contact_phone": "+221 33 864 17 17", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Autorent (location voiture)','Voiture','Location — Voiture. Contact : +221 33 889 01 21 · Boulevard du Centenaire. Tarif sur devis.','Autorent (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 889 01 21 · sur devis", "annonceur": "Autorent (location voiture)", "contact_phone": "+221 33 889 01 21", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Budget Sénégal (location voiture)','Voiture','Location — Voiture. Contact : +221 33 859 04 80 · Boulevard du Centenaire. Tarif sur devis.','Budget Sénégal (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 859 04 80 · sur devis", "annonceur": "Budget Sénégal (location voiture)", "contact_phone": "+221 33 859 04 80", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Europcar Sénégal (location voiture)','Voiture','Location — Voiture. Contact : +221 33 869 30 66 · Avenue Faidherbe Plateau. Tarif sur devis.','Europcar Sénégal (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 869 30 66 · sur devis", "annonceur": "Europcar Sénégal (location voiture)", "contact_phone": "+221 33 869 30 66", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Hertz Transacauto (location voiture)','Voiture','Location — Voiture. Contact : +221 33 889 81 81 · Rue Joseph Gomis Plateau. Tarif sur devis.','Hertz Transacauto (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 889 81 81 · sur devis", "annonceur": "Hertz Transacauto (location voiture)", "contact_phone": "+221 33 889 81 81", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Assurcar (location voiture)','Voiture','Location — Voiture. Contact : +221 33 823 72 50 · Rue Mohamed V Plateau. Tarif sur devis.','Assurcar (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 823 72 50 · sur devis", "annonceur": "Assurcar (location voiture)", "contact_phone": "+221 33 823 72 50", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Alliance G (location voiture)','Voiture','Location — Voiture. Contact : +221 33 868 34 23 · Grand Ngor. Tarif sur devis.','Alliance G (location voiture)','{"category": "Voiture", "region": "Dakar", "condition": "☎ +221 33 868 34 23 · sur devis", "annonceur": "Alliance G (location voiture)", "contact_phone": "+221 33 868 34 23", "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Locapro Sénégal (location matériel BTP/événementiel)','Événementiel','Location — Événementiel. Contact : locapro-senegal.com. Tarif sur devis.','Locapro Sénégal (location matériel BTP/événementiel)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Locapro Sénégal (location matériel BTP/événementiel)", "contact_phone": null, "contact_source": "locapro-senegal.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Kobe BTP (location engins/matériel)','BTP/Énergie','Location — BTP/Énergie. Contact : kobe-btp.com. Tarif sur devis.','Kobe BTP (location engins/matériel)','{"category": "BTP/Énergie", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Kobe BTP (location engins/matériel)", "contact_phone": null, "contact_source": "kobe-btp.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Sutura BTP (location groupe électrogène)','BTP/Énergie','Location — BTP/Énergie. Contact : suturabtp.com. Tarif sur devis.','Sutura BTP (location groupe électrogène)','{"category": "BTP/Énergie", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Sutura BTP (location groupe électrogène)", "contact_phone": null, "contact_source": "suturabtp.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Diallo BTP Logistique (location engins/échafaudage)','BTP/Énergie','Location — BTP/Énergie. Contact : diallobtp.com. Tarif sur devis.','Diallo BTP Logistique (location engins/échafaudage)','{"category": "BTP/Énergie", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Diallo BTP Logistique (location engins/échafaudage)", "contact_phone": null, "contact_source": "diallobtp.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Location 4x4 Sénégal','Voiture','Location — Voiture. Contact : +221 77 235 82 08. Tarif sur devis.','Location 4x4 Sénégal','{"category": "Voiture", "region": "Thiès", "condition": "☎ +221 77 235 82 08 · sur devis", "annonceur": "Location 4x4 Sénégal", "contact_phone": "+221 77 235 82 08", "contact_source": "senegal-online.com", "ville": "La Somone", "is_vitrine": true}'::jsonb),
('Ngaparou Aventures (location véhicule)','Voiture','Location — Voiture. Contact : +221 33 958 53 97. Tarif sur devis.','Ngaparou Aventures (location véhicule)','{"category": "Voiture", "region": "Thiès", "condition": "☎ +221 33 958 53 97 · sur devis", "annonceur": "Ngaparou Aventures (location véhicule)", "contact_phone": "+221 33 958 53 97", "contact_source": "senegal-online.com", "ville": "Ngaparou", "is_vitrine": true}'::jsonb),
('Nianing Automobiles (location véhicule)','Voiture','Location — Voiture. Contact : +221 33 954 92 30. Tarif sur devis.','Nianing Automobiles (location véhicule)','{"category": "Voiture", "region": "Thiès", "condition": "☎ +221 33 954 92 30 · sur devis", "annonceur": "Nianing Automobiles (location véhicule)", "contact_phone": "+221 33 954 92 30", "contact_source": "senegal-online.com", "ville": "Nianing", "is_vitrine": true}'::jsonb),
('Dakar Location Vaisselle (matériel réception)','Événementiel','Location — Événementiel. Contact : facebook.com/1Dakarvaisselle. Tarif sur devis.','Dakar Location Vaisselle (matériel réception)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Dakar Location Vaisselle (matériel réception)", "contact_phone": null, "contact_source": "facebook.com/1Dakarvaisselle", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('SENEDI SM Events (page Facebook)','Location','Location — Location. Contact : facebook.com/senedism. Tarif sur devis.','SENEDI SM Events (page Facebook)','{"category": "Location", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "SENEDI SM Events (page Facebook)", "contact_phone": null, "contact_source": "facebook.com/senedism", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Ayuf Holding (page Facebook)','Location','Location — Location. Contact : facebook.com/ayufholding. Tarif sur devis.','Ayuf Holding (page Facebook)','{"category": "Location", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Ayuf Holding (page Facebook)", "contact_phone": null, "contact_source": "facebook.com/ayufholding", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Location tables chaises tente réception (CoinAfrique)','Événementiel','Location — Événementiel. Contact : sn.coinafrique.com · En ligne. Tarif sur devis.','Location tables chaises tente réception (CoinAfrique)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Location tables chaises tente réception (CoinAfrique)", "contact_phone": null, "contact_source": "sn.coinafrique.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('X''Trem Jet Sénégal (jet ski Saly)','Nautique','Location — Nautique. Contact : facebook.com/xtremjetsenegal · Plage Royal Saly Hotel. Tarif sur devis.','X''Trem Jet Sénégal (jet ski Saly)','{"category": "Nautique", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "X''Trem Jet Sénégal (jet ski Saly)", "contact_phone": null, "contact_source": "facebook.com/xtremjetsenegal", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Saly Aventure (pêche et jet ski)','Nautique','Location — Nautique. Contact : salyaventure.com. Tarif sur devis.','Saly Aventure (pêche et jet ski)','{"category": "Nautique", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Saly Aventure (pêche et jet ski)", "contact_phone": null, "contact_source": "salyaventure.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Casa Loisirs (jet ski paddleboard Saly)','Nautique','Location — Nautique. Contact : +221 77 910 10 45 · Plage de Saly. Tarif sur devis.','Casa Loisirs (jet ski paddleboard Saly)','{"category": "Nautique", "region": "Thiès", "condition": "☎ +221 77 910 10 45 · sur devis", "annonceur": "Casa Loisirs (jet ski paddleboard Saly)", "contact_phone": "+221 77 910 10 45", "contact_source": "ilove-senegal.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Monaco Beach Boby Jet Ski (Dakar)','Nautique','Location — Nautique. Contact : bonjoursenegal.com · Hann Bel Air. Tarif sur devis.','Monaco Beach Boby Jet Ski (Dakar)','{"category": "Nautique", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Monaco Beach Boby Jet Ski (Dakar)", "contact_phone": null, "contact_source": "bonjoursenegal.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Moto Découverte Sénégal (moto/scooter Saly)','Moto/Scooter','Location — Moto/Scooter. Contact : facebook.com/p/Moto-Decouverte-Senegal-100088553737198. Tarif sur devis.','Moto Découverte Sénégal (moto/scooter Saly)','{"category": "Moto/Scooter", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Moto Découverte Sénégal (moto/scooter Saly)", "contact_phone": null, "contact_source": "facebook.com/p/Moto-Decouverte-Senegal-100088553737198", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Location motos et scooters Sénégal (Dakar)','Moto/Scooter','Location — Moto/Scooter. Contact : facebook.com/locationmotodkr. Tarif sur devis.','Location motos et scooters Sénégal (Dakar)','{"category": "Moto/Scooter", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Location motos et scooters Sénégal (Dakar)", "contact_phone": null, "contact_source": "facebook.com/locationmotodkr", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Location Moto Senegal (circuits et randonnées)','Moto/Scooter','Location — Moto/Scooter. Contact : location-moto-senegal.com. Tarif sur devis.','Location Moto Senegal (circuits et randonnées)','{"category": "Moto/Scooter", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Location Moto Senegal (circuits et randonnées)", "contact_phone": null, "contact_source": "location-moto-senegal.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Just married (location robes mariage Dakar)','Mode/Mariage','Location — Mode/Mariage. Contact : facebook.com/p/Just-married-100064357975757. Tarif sur devis.','Just married (location robes mariage Dakar)','{"category": "Mode/Mariage", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Just married (location robes mariage Dakar)", "contact_phone": null, "contact_source": "facebook.com/p/Just-married-100064357975757", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('La promise Bridal Dakar (robes mariage)','Mode/Mariage','Location — Mode/Mariage. Contact : facebook.com/lapromisebridaldakar. Tarif sur devis.','La promise Bridal Dakar (robes mariage)','{"category": "Mode/Mariage", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "La promise Bridal Dakar (robes mariage)", "contact_phone": null, "contact_source": "facebook.com/lapromisebridaldakar", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('The Day of Today (location vente robes Sénégal)','Mode/Mariage','Location — Mode/Mariage. Contact : facebook.com/thedayoftoday. Tarif sur devis.','The Day of Today (location vente robes Sénégal)','{"category": "Mode/Mariage", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "The Day of Today (location vente robes Sénégal)", "contact_phone": null, "contact_source": "facebook.com/thedayoftoday", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Mondial Business Mobus (vidéoprojecteur/IT)','Audiovisuel/IT','Location — Audiovisuel/IT. Contact : +221 77 627 09 09 · Derrière Belle Dame Couture Colobane. Tarif sur devis.','Mondial Business Mobus (vidéoprojecteur/IT)','{"category": "Audiovisuel/IT", "region": "Dakar", "condition": "☎ +221 77 627 09 09 · sur devis", "annonceur": "Mondial Business Mobus (vidéoprojecteur/IT)", "contact_phone": "+221 77 627 09 09", "contact_source": "planete-senegal.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Dakar Vidéo projecteur location service','Audiovisuel/IT','Location — Audiovisuel/IT. Contact : facebook.com/p/Dakar-Video-projecteur-100067804562667. Tarif sur devis.','Dakar Vidéo projecteur location service','{"category": "Audiovisuel/IT", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Dakar Vidéo projecteur location service", "contact_phone": null, "contact_source": "facebook.com/p/Dakar-Video-projecteur-100067804562667", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Africa Bâches (tentes bâches location)','Événementiel','Location — Événementiel. Contact : facebook.com/bachesAFRICA. Tarif sur devis.','Africa Bâches (tentes bâches location)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Africa Bâches (tentes bâches location)", "contact_phone": null, "contact_source": "facebook.com/bachesAFRICA", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('TOUBA BACHE du Sénégal (bâches événementiel)','Événementiel','Location — Événementiel. Contact : facebook.com/1299739596843469. Tarif sur devis.','TOUBA BACHE du Sénégal (bâches événementiel)','{"category": "Événementiel", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "TOUBA BACHE du Sénégal (bâches événementiel)", "contact_phone": null, "contact_source": "facebook.com/1299739596843469", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('DAKAR Coworking (salles réunion/espaces)','Espace/Bureau','Location — Espace/Bureau. Contact : +221 77 332 81 87 · Dieuppeul II Rue 13 Villa 2396. Tarif sur devis.','DAKAR Coworking (salles réunion/espaces)','{"category": "Espace/Bureau", "region": "Dakar", "condition": "☎ +221 77 332 81 87 · sur devis", "annonceur": "DAKAR Coworking (salles réunion/espaces)", "contact_phone": "+221 77 332 81 87", "contact_source": "facebook.com/p/DAKAR-Coworking-100088264518757", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Dakar CoWorking (salles réunion par heure)','Espace/Bureau','Location — Espace/Bureau. Contact : dakarcoworking.com. Tarif sur devis.','Dakar CoWorking (salles réunion par heure)','{"category": "Espace/Bureau", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Dakar CoWorking (salles réunion par heure)", "contact_phone": null, "contact_source": "dakarcoworking.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Freepenseur (coworking 24/7 Sud Foire)','Espace/Bureau','Location — Espace/Bureau. Contact : freepenseur.net · Immeuble Soda Marième Sud Foire. Tarif sur devis.','Freepenseur (coworking 24/7 Sud Foire)','{"category": "Espace/Bureau", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Freepenseur (coworking 24/7 Sud Foire)", "contact_phone": null, "contact_source": "freepenseur.net", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Waypoint Dakar (coworking 24/7)','Espace/Bureau','Location — Espace/Bureau. Contact : espacewaypoint.com. Tarif sur devis.','Waypoint Dakar (coworking 24/7)','{"category": "Espace/Bureau", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Waypoint Dakar (coworking 24/7)", "contact_phone": null, "contact_source": "espacewaypoint.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Nomad Foodtruck Sénégal (food truck mobile)','Food truck','Location — Food truck. Contact : facebook.com/foodtrucknomadsn. Tarif sur devis.','Nomad Foodtruck Sénégal (food truck mobile)','{"category": "Food truck", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Nomad Foodtruck Sénégal (food truck mobile)", "contact_phone": null, "contact_source": "facebook.com/foodtrucknomadsn", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Easy Quad Saly (location quad/buggy)','Quad/Aventure','Location — Quad/Aventure. Contact : easyquadsaly.com. Tarif sur devis.','Easy Quad Saly (location quad/buggy)','{"category": "Quad/Aventure", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Easy Quad Saly (location quad/buggy)", "contact_phone": null, "contact_source": "easyquadsaly.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('AFRICA Raids (quad/buggy Saly)','Quad/Aventure','Location — Quad/Aventure. Contact : +221 33 954 97 22 · Route de Saly Carrefour. Tarif sur devis.','AFRICA Raids (quad/buggy Saly)','{"category": "Quad/Aventure", "region": "Thiès", "condition": "☎ +221 33 954 97 22 · sur devis", "annonceur": "AFRICA Raids (quad/buggy Saly)", "contact_phone": "+221 33 954 97 22", "contact_source": "africa-raids.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Saly Loisirs (quad karting jet ski)','Nautique','Location — Nautique. Contact : saly-loisirs.com. Tarif sur devis.','Saly Loisirs (quad karting jet ski)','{"category": "Nautique", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Saly Loisirs (quad karting jet ski)", "contact_phone": null, "contact_source": "saly-loisirs.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Pape Loisirs (buggy/quad excursions)','Quad/Aventure','Location — Quad/Aventure. Contact : pape-loisirs.com · Saly Village. Tarif sur devis.','Pape Loisirs (buggy/quad excursions)','{"category": "Quad/Aventure", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "Pape Loisirs (buggy/quad excursions)", "contact_phone": null, "contact_source": "pape-loisirs.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('KART''ing Saly (karting Ngaparou)','Quad/Aventure','Location — Quad/Aventure. Contact : +221 33 958 50 02 · Route de Saly face station API. Tarif sur devis.','KART''ing Saly (karting Ngaparou)','{"category": "Quad/Aventure", "region": "Thiès", "condition": "☎ +221 33 958 50 02 · sur devis", "annonceur": "KART''ing Saly (karting Ngaparou)", "contact_phone": "+221 33 958 50 02", "contact_source": "facebook.com/kartingsaly", "ville": "Ngaparou", "is_vitrine": true}'::jsonb),
('Malika Surf Camp (cours surf Dakar)','Nautique','Location — Nautique. Contact : planete-senegal.com · Plage Yoff BCEAO. Tarif sur devis.','Malika Surf Camp (cours surf Dakar)','{"category": "Nautique", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Malika Surf Camp (cours surf Dakar)", "contact_phone": null, "contact_source": "planete-senegal.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Oceanium de Dakar (kayak/activités nautiques)','Nautique','Location — Nautique. Contact : senegal-online.com · Corniche Ouest. Tarif sur devis.','Oceanium de Dakar (kayak/activités nautiques)','{"category": "Nautique", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Oceanium de Dakar (kayak/activités nautiques)", "contact_phone": null, "contact_source": "senegal-online.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('DaKite Sénégal (kitesurf Saly)','Nautique','Location — Nautique. Contact : dakite.au-senegal.com · Plage de Saly. Tarif sur devis.','DaKite Sénégal (kitesurf Saly)','{"category": "Nautique", "region": "Thiès", "condition": "Sur devis — voir contact", "annonceur": "DaKite Sénégal (kitesurf Saly)", "contact_phone": null, "contact_source": "dakite.au-senegal.com", "ville": "Saly", "is_vitrine": true}'::jsonb),
('Fun Spa Dakar (jacuzzi gonflable à domicile)','Bien-être','Location — Bien-être. Contact : funspa.sn. Tarif sur devis.','Fun Spa Dakar (jacuzzi gonflable à domicile)','{"category": "Bien-être", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Fun Spa Dakar (jacuzzi gonflable à domicile)", "contact_phone": null, "contact_source": "funspa.sn", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('VIP Spa Jacuzzi Massage (page Facebook)','Bien-être','Location — Bien-être. Contact : facebook.com/VIPSPAJACUZZI. Tarif sur devis.','VIP Spa Jacuzzi Massage (page Facebook)','{"category": "Bien-être", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "VIP Spa Jacuzzi Massage (page Facebook)", "contact_phone": null, "contact_source": "facebook.com/VIPSPAJACUZZI", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('King Mascotte (mascotte/animations enfants)','Animation enfants','Location — Animation enfants. Contact : +221 77 350 84 37 · Zone de Captage Dakar. Tarif sur devis.','King Mascotte (mascotte/animations enfants)','{"category": "Animation enfants", "region": "Dakar", "condition": "☎ +221 77 350 84 37 · sur devis", "annonceur": "King Mascotte (mascotte/animations enfants)", "contact_phone": "+221 77 350 84 37", "contact_source": "sites.google.com/nelamservices.com/kingmascotte", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Kid''Air (château gonflable/events enfants)','Animation enfants','Location — Animation enfants. Contact : frenchside.co.za/kidair.net. Tarif sur devis.','Kid''Air (château gonflable/events enfants)','{"category": "Animation enfants", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Kid''Air (château gonflable/events enfants)", "contact_phone": null, "contact_source": "frenchside.co.za/kidair.net", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('FUN CITY Dakar (clowns/magiciens/animations)','Animation enfants','Location — Animation enfants. Contact : funcity.sn · 1 Avenue Malick Sy. Tarif sur devis.','FUN CITY Dakar (clowns/magiciens/animations)','{"category": "Animation enfants", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "FUN CITY Dakar (clowns/magiciens/animations)", "contact_phone": null, "contact_source": "funcity.sn", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Terrou-Bi (location bateau/pêche sportive)','Pêche/Bateau','Location — Pêche/Bateau. Contact : terroubi.com · Marina Terrou-Bi Corniche Est. Tarif sur devis.','Terrou-Bi (location bateau/pêche sportive)','{"category": "Pêche/Bateau", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Terrou-Bi (location bateau/pêche sportive)", "contact_phone": null, "contact_source": "terroubi.com", "ville": "Dakar", "is_vitrine": true}'::jsonb),
('Wonder Park Dakar (parc aquatique/loisirs)','Loisirs','Location — Loisirs. Contact : tiktok.com/@wonderparkdakar. Tarif sur devis.','Wonder Park Dakar (parc aquatique/loisirs)','{"category": "Loisirs", "region": "Dakar", "condition": "Sur devis — voir contact", "annonceur": "Wonder Park Dakar (parc aquatique/loisirs)", "contact_phone": null, "contact_source": "tiktok.com/@wonderparkdakar", "ville": "Dakar", "is_vitrine": true}'::jsonb);

with adm as (select id from public.profiles where role='admin' order by created_at asc limit 1)
insert into public.products(name,category,price,stock,description,vendor_id,vendor_name,active,is_rental,rental_specs)
select l.name,l.category,1,1,l.description,(select id from adm),l.vendor_name,true,true,l.rental_specs
  from _loueurs l
 where not exists (select 1 from public.products p where p.vendor_id=(select id from adm) and p.name=l.name and coalesce(p.is_rental,false)=true);

select 'loueurs_vitrine' as type, count(*) as n from _loueurs;
