-- ============================================================================
-- CATALOGUE : place les annonces Immobilier (module Immobilier) + Location (NEXUS
-- Location) sur le site, ATTRIBUEES AU COMPTE ADMIN (vendor_id = admin). Le nom de
-- l'agence reste dans products.vendor_name, et le contact (annonceur + telephone) est
-- conserve dans les specs. Prix en EUR (FCFA / 655.957). Idempotent (skip si present).
-- ============================================================================

-- Garde-fou : il faut un compte admin.
do $$ begin
  if not exists (select 1 from public.profiles where role='admin') then
    raise exception 'Aucun compte admin (profiles.role=admin) — impossible d''attribuer les annonces.';
  end if;
end $$;

drop table if exists _annonces;
create temp table _annonces(name text, category text, price_eur numeric, description text, image_url text, vendor_name text, is_rental bool, rental_specs jsonb, is_realestate bool, realestate_specs jsonb);
insert into _annonces values
('Studio meublé Mermoz','Immobilier',381.12,'Studio neuf entièrement meublé. Cuisine équipée climatisation WiFi. Idéal cadre en mission.',null,'DAIDY Immobilier',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 250000, "surface_m2": 35, "rooms": 1, "bedrooms": 1, "bathrooms": 1, "furnished": true, "region": "Dakar", "location_label": "Mermoz", "annonceur": "DAIDY Immobilier", "contact_phone": "+221 77 640 44 68"}'::jsonb),
('Appartement F2 Sacré-Cœur 3','Immobilier',579.31,'Appartement lumineux au 3e étage. Séjour chambre cuisine salle de bain. Eau et électricité non inclus.',null,'3M Immobilier',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 380000, "surface_m2": 65, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Sacré-Cœur 3", "annonceur": "3M Immobilier", "contact_phone": "+221 33 867 00 56"}'::jsonb),
('Appartement F3 VDN standing','Immobilier',838.47,'Grand appartement côté VDN. 2 chambres séjour 2 douches. Gardien et parking.',null,'Kings Plaza',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 550000, "surface_m2": 90, "rooms": 3, "bedrooms": 2, "bathrooms": 2, "furnished": false, "region": "Dakar", "location_label": "VDN", "annonceur": "Kings Plaza", "contact_phone": "+221 33 860 40 19"}'::jsonb),
('Villa F4 meublée Point E','Immobilier',1372.04,'Villa avec jardin et terrasse. 3 chambres avec lits cuisine équipée clim dans toutes les pièces.',null,'NIDMIKS',false,null,true,'{"transaction": "location", "property_type": "villa", "price_fcfa": 900000, "surface_m2": 180, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": true, "region": "Dakar", "location_label": "Point E", "annonceur": "NIDMIKS", "contact_phone": "+221 77 512 34 00"}'::jsonb),
('Appartement F2 HLM 5','Immobilier',426.86,'Appartement propre et sécurisé. Quartier calme proche marché HLM 5. Libre de suite.',null,'Immolux',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 280000, "surface_m2": 60, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "HLM 5", "annonceur": "Immolux", "contact_phone": "+221 77 232 42 03"}'::jsonb),
('Studio Plateau centre-ville','Immobilier',304.9,'Studio meublé immeuble sécurisé. Idéal professionnel. Proche BCEAO et ministères.',null,'Agence Citron Vert',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 200000, "surface_m2": 30, "rooms": 1, "bedrooms": 1, "bathrooms": 1, "furnished": true, "region": "Dakar", "location_label": "Plateau", "annonceur": "Agence Citron Vert", "contact_phone": "+221 77 573 90 32"}'::jsonb),
('Villa F5 Fann Résidence','Immobilier',2286.74,'Villa prestige avec piscine jardin 4 chambres suite vue mer partielle. Sécurité 24h.',null,'Dakar Hermitage Immobilier',false,null,true,'{"transaction": "location", "property_type": "villa", "price_fcfa": 1500000, "surface_m2": 280, "rooms": 5, "bedrooms": 4, "bathrooms": 3, "furnished": true, "region": "Dakar", "location_label": "Fann Résidence", "annonceur": "Dakar Hermitage Immobilier", "contact_phone": "+221 76 683 36 62"}'::jsonb),
('Bureau 80m² Plateau','Immobilier',914.69,'Open space 80m² avec 2 salles de réunion kitchenette parking. Réseau fibre disponible.',null,'RIM Sénégal',false,null,true,'{"transaction": "location", "property_type": "bureau", "price_fcfa": 600000, "surface_m2": 80, "rooms": 3, "bedrooms": null, "bathrooms": 2, "furnished": false, "region": "Dakar", "location_label": "Plateau", "annonceur": "RIM Sénégal", "contact_phone": "Voir site"}'::jsonb),
('Appartement F3 Liberté 6','Immobilier',686.02,'3 pièces 1er étage. 2 chambres séjour cuisine WC séparé. Gardien et interphone.',null,'Agence Djinguil Immobilier',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 450000, "surface_m2": 85, "rooms": 3, "bedrooms": 2, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Liberté 6", "annonceur": "Agence Djinguil Immobilier", "contact_phone": "+221 33 867 61 11"}'::jsonb),
('Studio Ouest Foire sécurisé','Immobilier',335.39,'Studio sécurisé résidence Ouest Foire. Eau courante électricité. Proche toutes commodités.',null,'Mbol Yama',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 220000, "surface_m2": 32, "rooms": 1, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Ouest Foire", "annonceur": "Mbol Yama", "contact_phone": "+221 77 635 93 16"}'::jsonb),
('Appartement F2 Saly vue mer','Immobilier',914.69,'F2 entièrement meublé avec terrasse vue mer. Résidence sécurisée avec piscine. Idéal vacances.',null,'Saly Immo',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 600000, "surface_m2": 70, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": true, "region": "Thiès", "location_label": "Saly", "annonceur": "Saly Immo", "contact_phone": "+221 78 475 57 56"}'::jsonb),
('Villa F4 Saly résidentiel','Immobilier',1829.39,'Belle villa avec jardin tropical et piscine. 3 chambres séjour climatisé cuisine équipée.',null,'Agipco Immobilier',false,null,true,'{"transaction": "location", "property_type": "villa", "price_fcfa": 1200000, "surface_m2": 220, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": true, "region": "Thiès", "location_label": "Saly", "annonceur": "Agipco Immobilier", "contact_phone": "+221 77 644 07 37"}'::jsonb),
('Appartement F3 Thiès centre','Immobilier',304.9,'3 pièces dans résidence calme Randoulène. Bon rapport qualité-prix. Libre de suite.',null,'Immothiès-Dakar',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 200000, "surface_m2": 75, "rooms": 3, "bedrooms": 2, "bathrooms": 1, "furnished": false, "region": "Thiès", "location_label": "Randoulène Nord", "annonceur": "Immothiès-Dakar", "contact_phone": "+221 77 143 71 25"}'::jsonb),
('Appartement F3 neuf Sacré-Cœur 3','Immobilier',68602.06,'Appartement neuf dans programme immobilier. 2 chambres 2 douches séjour parking.',null,'Cabinet Immobilier du Monde',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 45000000, "surface_m2": 90, "rooms": 3, "bedrooms": 2, "bathrooms": 2, "furnished": false, "region": "Dakar", "location_label": "Sacré-Cœur 3", "annonceur": "Cabinet Immobilier du Monde", "contact_phone": "+221 77 537 18 19"}'::jsonb),
('Studio neuf VDN investissement locatif','Immobilier',27440.82,'Studio neuf avec vue dégagée. Idéal investissement locatif. Rendement 7-8% estimé.',null,'Kings Plaza',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 18000000, "surface_m2": 38, "rooms": 1, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "VDN", "annonceur": "Kings Plaza", "contact_phone": "+221 33 860 40 19"}'::jsonb),
('Villa F5 Point E calme','Immobilier',182938.82,'Belle villa en R+1 avec terrasse jardin et double garage. À rénover partiellement.',null,'Résidence Arcanes',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 120000000, "surface_m2": 250, "rooms": 5, "bedrooms": 4, "bathrooms": 3, "furnished": false, "region": "Dakar", "location_label": "Point E", "annonceur": "Résidence Arcanes", "contact_phone": "+221 33 824 37 70"}'::jsonb),
('Appartement F4 Mermoz 2e étage','Immobilier',99091.86,'Grand appartement en bon état. 3 chambres 2 salles de bain grande terrasse.',null,'Saphir Immobilier',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 65000000, "surface_m2": 110, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": false, "region": "Dakar", "location_label": "Mermoz", "annonceur": "Saphir Immobilier", "contact_phone": "+221 33 860 04 74"}'::jsonb),
('Terrain viabilisé 300m² SICAP Baobab','Immobilier',33538.78,'Terrain viabilisé titré TF. Eau et électricité en bordure. Idéal construction villa.',null,'Group MBS Immo',false,null,true,'{"transaction": "vente", "property_type": "terrain", "price_fcfa": 22000000, "surface_m2": 300, "rooms": null, "bedrooms": null, "bathrooms": null, "furnished": false, "region": "Dakar", "location_label": "SICAP Baobab", "annonceur": "Group MBS Immo", "contact_phone": "+221 77 513 52 01"}'::jsonb),
('Villa F6 Corniche Ouest prestige','Immobilier',426857.25,'Propriété de prestige avec vue mer panoramique. Piscine spa jardin paysager 600m².',null,'Dakar Hermitage Immobilier',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 280000000, "surface_m2": 420, "rooms": 6, "bedrooms": 5, "bathrooms": 4, "furnished": true, "region": "Dakar", "location_label": "Corniche Ouest", "annonceur": "Dakar Hermitage Immobilier", "contact_phone": "+221 76 683 36 62"}'::jsonb),
('Local commercial Plateau 60m²','Immobilier',83846.96,'Local commercial rez-de-chaussée rue passante. Devanture 6m. Idéal boutique ou agence.',null,'Services Immobiliers SARL',false,null,true,'{"transaction": "vente", "property_type": "local commercial", "price_fcfa": 55000000, "surface_m2": 60, "rooms": 1, "bedrooms": null, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Plateau", "annonceur": "Services Immobiliers SARL", "contact_phone": "+221 76 682 26 26"}'::jsonb),
('Appartement F2 Liberté 6 locatif','Immobilier',38112.25,'F2 en bon état résidence sécurisée. Actuellement en location 250 000 F par mois.',null,'Flèche Immo',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 25000000, "surface_m2": 55, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Liberté 6", "annonceur": "Flèche Immo", "contact_phone": "+221 33 867 17 91"}'::jsonb),
('Immeuble R+2 HLM de rapport','Immobilier',274408.23,'Immeuble de rapport 3 niveaux : 3 appartements F3 par étage. Rendement locatif élevé.',null,'Immobilière Dado',false,null,true,'{"transaction": "vente", "property_type": "immeuble", "price_fcfa": 180000000, "surface_m2": 380, "rooms": 9, "bedrooms": 9, "bathrooms": 6, "furnished": false, "region": "Dakar", "location_label": "HLM 5", "annonceur": "Immobilière Dado", "contact_phone": "+221 77 374 74 89"}'::jsonb),
('Bureau 120m² Grand-Yoff','Immobilier',73175.53,'Plateau bureau dans résidence sécurisée. Salles de réunion parking 3 véhicules.',null,'Immo Access',false,null,true,'{"transaction": "vente", "property_type": "bureau", "price_fcfa": 48000000, "surface_m2": 120, "rooms": 4, "bedrooms": null, "bathrooms": 2, "furnished": false, "region": "Dakar", "location_label": "Grand-Yoff", "annonceur": "Immo Access", "contact_phone": "+221 77 532 59 94"}'::jsonb),
('Villa F5 bord de mer Saly','Immobilier',182938.82,'Villa de standing avec accès direct plage. Piscine patio garage 2 voitures. Titre foncier.',null,'ImmoTop Saly',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 120000000, "surface_m2": 320, "rooms": 5, "bedrooms": 4, "bathrooms": 3, "furnished": true, "region": "Thiès", "location_label": "Saly", "annonceur": "ImmoTop Saly", "contact_phone": "Voir site"}'::jsonb),
('Terrain résidentiel Saly 400m²','Immobilier',30489.8,'Terrain titré dans lotissement résidentiel de Saly. Toutes commodités à proximité.',null,'Saly Immobilier',false,null,true,'{"transaction": "vente", "property_type": "terrain", "price_fcfa": 20000000, "surface_m2": 400, "rooms": null, "bedrooms": null, "bathrooms": null, "furnished": null, "region": "Thiès", "location_label": "Saly", "annonceur": "Saly Immobilier", "contact_phone": "+221 33 954 97 46"}'::jsonb),
('Appartement F3 Saly résidentiel','Immobilier',57930.63,'Appartement dans résidence gardée avec piscine commune. 2 chambres terrasse 15m².',null,'Afriquimmo',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 38000000, "surface_m2": 85, "rooms": 3, "bedrooms": 2, "bathrooms": 2, "furnished": false, "region": "Thiès", "location_label": "Saly", "annonceur": "Afriquimmo", "contact_phone": "+221 77 569 35 61"}'::jsonb),
('Villa F4 Mbour bord de mer','Immobilier',106714.31,'Villa F4 à 500m de la plage de Mbour. Jardin 300m² garage citerne eau.',null,'Immobilier La Lagune',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 70000000, "surface_m2": 200, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": false, "region": "Thiès", "location_label": "Mbour", "annonceur": "Immobilier La Lagune", "contact_phone": "Voir site"}'::jsonb),
('Terrain industriel 1000m² Thiès','Immobilier',68602.06,'Terrain clôturé en zone industrielle de Thiès. Gardien eau électricité. Idéal entrepôt.',null,'Immothiès-Dakar',false,null,true,'{"transaction": "vente", "property_type": "terrain", "price_fcfa": 45000000, "surface_m2": 1000, "rooms": null, "bedrooms": null, "bathrooms": null, "furnished": false, "region": "Thiès", "location_label": "Zone industrielle", "annonceur": "Immothiès-Dakar", "contact_phone": "+221 77 143 71 25"}'::jsonb),
('Villa F6 Ngaparou prestige','Immobilier',381122.54,'Demeure de luxe en retrait de la RN1. Piscine à débordement pergola pool-house. Sécurisée.',null,'Saly Immo',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 250000000, "surface_m2": 500, "rooms": 6, "bedrooms": 5, "bathrooms": 4, "furnished": true, "region": "Thiès", "location_label": "Ngaparou", "annonceur": "Saly Immo", "contact_phone": "+221 78 475 57 56"}'::jsonb),
('Studio Thiès centre investissement','Immobilier',15244.9,'Studio accessible. Idéal pour premier investissement immobilier. Quartier Randoulène.',null,'Immothiès-Dakar',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 10000000, "surface_m2": 28, "rooms": 1, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Thiès", "location_label": "Randoulène Nord", "annonceur": "Immothiès-Dakar", "contact_phone": "+221 77 143 71 25"}'::jsonb),
('Appartement F3 Saint-Louis centre','Immobilier',274.41,'F3 dans maison coloniale rénovée. Île de Saint-Louis patrimoine UNESCO. Proche fleuve Sénégal.',null,'SAINT LOUIS Immobilier',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 180000, "surface_m2": 70, "rooms": 3, "bedrooms": 2, "bathrooms": 1, "furnished": false, "region": "Saint-Louis", "location_label": "Île Saint-Louis", "annonceur": "SAINT LOUIS Immobilier", "contact_phone": "Voir Facebook"}'::jsonb),
('Villa F4 Saint-Louis Nord','Immobilier',53357.16,'Villa dans quartier résidentiel nord. Jardin 200m² citerne double. À 10 min de la plage de Guet-Ndar.',null,'Agence Immobilière Saint-Louis du Sénégal',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 35000000, "surface_m2": 180, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": false, "region": "Saint-Louis", "location_label": "Guet-Ndar", "annonceur": "Agence Immobilière Saint-Louis du Sénégal", "contact_phone": "Voir Facebook"}'::jsonb),
('Appartement F2 Ziguinchor','Immobilier',182.94,'Appartement au cœur de Ziguinchor. Climatisation eau courante. Proche port et marché.',null,'L''immobilier à Ziguinchor',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 120000, "surface_m2": 60, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Ziguinchor", "location_label": "Centre Ziguinchor", "annonceur": "L''immobilier à Ziguinchor", "contact_phone": "Voir Facebook"}'::jsonb),
('Terrain constructible Ziguinchor 500m²','Immobilier',18293.88,'Terrain titré à Boudody. Zone calme résidentielle. Toutes commodités en bordure. Idéal villa.',null,'L''immobilier à Ziguinchor',false,null,true,'{"transaction": "vente", "property_type": "terrain", "price_fcfa": 12000000, "surface_m2": 500, "rooms": null, "bedrooms": null, "bathrooms": null, "furnished": false, "region": "Ziguinchor", "location_label": "Boudody", "annonceur": "L''immobilier à Ziguinchor", "contact_phone": "Voir Facebook"}'::jsonb),
('Appartement F3 Kaolack Médina','Immobilier',228.67,'3 pièces en pleine Médina. Eau électricité inclus. Proche Grand Marché de Kaolack.',null,'Agence Immobilière Kaolack',false,null,true,'{"transaction": "location", "property_type": "appartement", "price_fcfa": 150000, "surface_m2": 75, "rooms": 3, "bedrooms": 2, "bathrooms": 1, "furnished": false, "region": "Kaolack", "location_label": "Médina Kaolack", "annonceur": "Agence Immobilière Kaolack", "contact_phone": "Voir annonce"}'::jsonb),
('Villa F4 Kaolack résidentiel','Immobilier',42685.72,'Belle villa avec jardin et citerne d''eau à Dialégne. Quartier calme et sécurisé. Titre foncier.',null,'Immo Kaolack',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 28000000, "surface_m2": 160, "rooms": 4, "bedrooms": 3, "bathrooms": 2, "furnished": false, "region": "Kaolack", "location_label": "Dialégne", "annonceur": "Immo Kaolack", "contact_phone": "Voir annonce"}'::jsonb),
('Terrain Touba 400m² viabilisé','Immobilier',12195.92,'Terrain titré dans extension Touba. Zone en développement rapide. Eau et électricité accessibles.',null,'TOUBA IMMO',false,null,true,'{"transaction": "vente", "property_type": "terrain", "price_fcfa": 8000000, "surface_m2": 400, "rooms": null, "bedrooms": null, "bathrooms": null, "furnished": false, "region": "Diourbel", "location_label": "Touba Ndamatou", "annonceur": "TOUBA IMMO", "contact_phone": "+221 77 108 88 89"}'::jsonb),
('Villa F5 Touba résidentiel','Immobilier',83846.96,'Grande villa dans quartier résidentiel de Touba. Mosquée centrale à 5 min. Jardin clôturé.',null,'TOUBA IMMO',false,null,true,'{"transaction": "vente", "property_type": "villa", "price_fcfa": 55000000, "surface_m2": 220, "rooms": 5, "bedrooms": 4, "bathrooms": 3, "furnished": false, "region": "Diourbel", "location_label": "Touba Darou Khoudoss", "annonceur": "TOUBA IMMO", "contact_phone": "+221 77 108 88 89"}'::jsonb),
('Appartement neuf F2 Almadies KALIA','Immobilier',83846.96,'Programme KALIA neuf. Finition haut de gamme. Option location-vente dès 317 000 FCFA/mois. Livraison 2026.',null,'Résidences KALIA',false,null,true,'{"transaction": "vente", "property_type": "appartement", "price_fcfa": 55000000, "surface_m2": 65, "rooms": 2, "bedrooms": 1, "bathrooms": 1, "furnished": false, "region": "Dakar", "location_label": "Almadies", "annonceur": "Résidences KALIA", "contact_phone": "+221 33 821 14 15"}'::jsonb),
('Toyota Corolla climatisée (auto)','Voiture',45.73,'Voiture de tourisme confortable avec climatisation et GPS. Chauffeur disponible en option.',null,'KAMA Automobile',true,'{"category": "Voiture", "price_per_day": 30000, "price_per_week": 180000, "deposit_fcfa": 100000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "KAMA Automobile", "contact_phone": "+221 78 454 79 79"}'::jsonb,false,null),
('Hyundai i10 économique','Voiture',30.49,'Citadine pratique pour se déplacer à Dakar. Carburant à la charge du locataire.',null,'SELOV',true,'{"category": "Voiture", "price_per_day": 20000, "price_per_week": 120000, "deposit_fcfa": 60000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "SELOV", "contact_phone": "+221 33 827 57 26"}'::jsonb,false,null),
('Toyota Land Cruiser Prado 4x4','Voiture',114.34,'4x4 idéal pour déplacements en brousse et inter-régions. Chauffeur disponible.',null,'Avis Sénégal',true,'{"category": "Voiture", "price_per_day": 75000, "price_per_week": 450000, "deposit_fcfa": 200000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Avis Sénégal", "contact_phone": "+221 33 849 77 55"}'::jsonb,false,null),
('Mercedes Classe E berline VIP','Voiture',137.2,'Berline de prestige pour mariages événements VIP et transferts aéroport.',null,'Alliance G',true,'{"category": "Voiture", "price_per_day": 90000, "price_per_week": 540000, "deposit_fcfa": 250000, "min_days": 1, "condition": "Excellent état", "region": "Dakar", "annonceur": "Alliance G", "contact_phone": "+221 33 868 34 23"}'::jsonb,false,null),
('Minibus 15 places Mercedes Sprinter','Voiture',91.47,'Idéal pour groupes excursions séminaires. Chauffeur inclus dans le prix.',null,'Autorent',true,'{"category": "Voiture", "price_per_day": 60000, "price_per_week": 360000, "deposit_fcfa": 150000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Autorent", "contact_phone": "+221 33 889 01 21"}'::jsonb,false,null),
('Renault Duster 4x4 Petite Côte','Voiture',68.6,'4x4 fiable pour découvrir la Petite Côte et ses environs. Carburant non inclus.',null,'Location 4x4 Sénégal',true,'{"category": "Voiture", "price_per_day": 45000, "price_per_week": 270000, "deposit_fcfa": 120000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Location 4x4 Sénégal", "contact_phone": "+221 77 235 82 08"}'::jsonb,false,null),
('Pickup utilitaire bâché double cab','Voiture',53.36,'Pickup double cab. Idéal transport de matériaux et petits chantiers.',null,'ADA Location de Véhicules',true,'{"category": "Voiture", "price_per_day": 35000, "price_per_week": 210000, "deposit_fcfa": 80000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "ADA Location de Véhicules", "contact_phone": "+221 33 869 25 26"}'::jsonb,false,null),
('Toyota HiAce 18 places (excursion)','Voiture',121.96,'Minibus pour excursions longue distance. Chauffeur expérimenté inclus.',null,'Budget Sénégal',true,'{"category": "Voiture", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 200000, "min_days": 2, "condition": "Bon état", "region": "Dakar", "annonceur": "Budget Sénégal", "contact_phone": "+221 33 859 04 80"}'::jsonb,false,null),
('Chapiteau 10×20m grande capacité','Événementiel',182.94,'Chapiteau pour 150-200 personnes. Livraison et installation incluses à Dakar.',null,'NERI GROUP',true,'{"category": "Événementiel", "price_per_day": 120000, "price_per_week": 720000, "deposit_fcfa": 200000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "NERI GROUP", "contact_phone": "+221 77 482 59 99"}'::jsonb,false,null),
('Tente pagode 5×5m (pose incluse)','Événementiel',68.6,'Tente blanche avec pose et dépose. Disponible en plusieurs couleurs. Livraison Dakar.',null,'DALLY BEST',true,'{"category": "Événementiel", "price_per_day": 45000, "price_per_week": 270000, "deposit_fcfa": 100000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "DALLY BEST", "contact_phone": "+221 76 941 82 40"}'::jsonb,false,null),
('Lot 100 chaises blanches Napoléon','Événementiel',30.49,'Chaises de réception blanches livrées à domicile. Housses disponibles en supplément.',null,'SENEDI SM Events',true,'{"category": "Événementiel", "price_per_day": 20000, "price_per_week": 120000, "deposit_fcfa": 40000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "SENEDI SM Events", "contact_phone": "Voir site"}'::jsonb,false,null),
('Tables rondes Ø180cm (lot 20)','Événementiel',38.11,'Tables rondes avec nappes. Livraison Dakar et banlieue incluse.',null,'Dakar Location Vaisselle',true,'{"category": "Événementiel", "price_per_day": 25000, "price_per_week": 150000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Dakar Location Vaisselle", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Sono complète DJ professionnelle','Événementiel',152.45,'Système son complet : enceintes JBL table de mixage micro. Technicien disponible en option.',null,'Ayuf Holding SN',true,'{"category": "Événementiel", "price_per_day": 100000, "price_per_week": 600000, "deposit_fcfa": 200000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Ayuf Holding SN", "contact_phone": "Voir site"}'::jsonb,false,null),
('Vaisselle complète lot 200 couverts','Événementiel',45.73,'Lot vaisselle (assiettes verres couverts plats de service) pour 200 personnes.',null,'DALLY BEST',true,'{"category": "Événementiel", "price_per_day": 30000, "price_per_week": 180000, "deposit_fcfa": 60000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "DALLY BEST", "contact_phone": "+221 76 941 82 40"}'::jsonb,false,null),
('Podium scène 4×6m H 1m','Événementiel',121.96,'Scène modulable idéale pour concerts discours défilés. Montage et démontage inclus.',null,'NERI GROUP',true,'{"category": "Événementiel", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 150000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "NERI GROUP", "contact_phone": "+221 77 482 59 99"}'::jsonb,false,null),
('Groupe électrogène silencieux 10 KVA','Événementiel',76.22,'Groupe électrogène silencieux pour événements. Carburant non inclus. Livraison Dakar.',null,'Sutura BTP',true,'{"category": "Événementiel", "price_per_day": 50000, "price_per_week": 300000, "deposit_fcfa": 100000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Sutura BTP", "contact_phone": "Voir site"}'::jsonb,false,null),
('Groupe électrogène chantier 50 KVA','BTP/Énergie',121.96,'Groupe électrogène chantier 50 KVA. Maintenance incluse. Carburant non inclus.',null,'Locapro Sénégal',true,'{"category": "BTP/Énergie", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 200000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Locapro Sénégal", "contact_phone": "Voir site"}'::jsonb,false,null),
('Bétonnière 350L électrique','BTP/Énergie',38.11,'Bétonnière de chantier 350L. Livraison sur Dakar et banlieue.',null,'Kobe BTP',true,'{"category": "BTP/Énergie", "price_per_day": 25000, "price_per_week": 150000, "deposit_fcfa": 60000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Kobe BTP", "contact_phone": "Voir site"}'::jsonb,false,null),
('Échafaudage tubulaire 50m² H 4m','BTP/Énergie',53.36,'Kit échafaudage complet : planchers montants garde-corps. Pose disponible en option.',null,'Diallo BTP Logistique',true,'{"category": "BTP/Énergie", "price_per_day": 35000, "price_per_week": 210000, "deposit_fcfa": 80000, "min_days": 3, "condition": "Bon état", "region": "Dakar", "annonceur": "Diallo BTP Logistique", "contact_phone": "Voir site"}'::jsonb,false,null),
('Compresseur d''air 200L chantier','BTP/Énergie',30.49,'Compresseur 200L pour pneumatique peinture clouage. Livraison Dakar.',null,'Locapro Sénégal',true,'{"category": "BTP/Énergie", "price_per_day": 20000, "price_per_week": 120000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Locapro Sénégal", "contact_phone": "Voir site"}'::jsonb,false,null),
('Nacelle élévatrice 12m','BTP/Énergie',182.94,'Nacelle télescopique 12 mètres. Idéal travaux en hauteur nettoyage façades. Opérateur disponible.',null,'Kobe BTP',true,'{"category": "BTP/Énergie", "price_per_day": 120000, "price_per_week": 720000, "deposit_fcfa": 250000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Kobe BTP", "contact_phone": "Voir site"}'::jsonb,false,null),
('Vibreur à béton électrique','BTP/Énergie',18.29,'Aiguille vibrante pour mise en oeuvre du béton. Livraison sur Dakar.',null,'Diallo BTP Logistique',true,'{"category": "BTP/Énergie", "price_per_day": 12000, "price_per_week": 72000, "deposit_fcfa": 30000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Diallo BTP Logistique", "contact_phone": "Voir site"}'::jsonb,false,null),
('Studio meublé Mermoz (nuit ou semaine)','Hébergement',45.73,'Studio climatisé tout équipé : WiFi cuisine équipée linge fourni. Proche plage Fann.',null,'Locadakar',true,'{"category": "Hébergement", "price_per_day": 30000, "price_per_week": 180000, "deposit_fcfa": 60000, "min_days": 2, "condition": "Très bon état", "region": "Dakar", "annonceur": "Locadakar", "contact_phone": "+221 77 555 55 70"}'::jsonb,false,null),
('Appartement F2 Saly Portudal','Hébergement',91.47,'Appartement 2 pièces avec terrasse et piscine partagée à 300m de la plage. WiFi inclus.',null,'Saly Immo',true,'{"category": "Hébergement", "price_per_day": 60000, "price_per_week": 360000, "deposit_fcfa": 120000, "min_days": 2, "condition": "Excellent état", "region": "Thiès", "annonceur": "Saly Immo", "contact_phone": "+221 78 475 57 56"}'::jsonb,false,null),
('Villa 4 pièces avec piscine Saly','Hébergement',266.79,'Villa familiale 4 chambres avec piscine privée jardin et 2 terrasses. Proche plage de Saly.',null,'ImmoTop Saly',true,'{"category": "Hébergement", "price_per_day": 175000, "price_per_week": 1050000, "deposit_fcfa": 350000, "min_days": 3, "condition": "Excellent état", "region": "Thiès", "annonceur": "ImmoTop Saly", "contact_phone": "Voir site"}'::jsonb,false,null),
('Maison de repos 3 pièces Mbour','Hébergement',68.6,'Maison calme avec cour ombragée. Idéal retraite et repos. WiFi et ménage hebdomadaire inclus.',null,'Immobilier La Lagune',true,'{"category": "Hébergement", "price_per_day": 45000, "price_per_week": 270000, "deposit_fcfa": 90000, "min_days": 2, "condition": "Très bon état", "region": "Thiès", "annonceur": "Immobilier La Lagune", "contact_phone": "Voir site"}'::jsonb,false,null),
('Jet ski Yamaha (session 20 min)','Nautique',38.11,'Location jet ski avec instructeur sur plage Royal Saly Hotel. Bouée tractée et wakeboard aussi disponibles.',null,'X''Trem Jet Sénégal',true,'{"category": "Nautique", "price_per_day": 25000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "X''Trem Jet Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Jet ski + bouée tractée (combo 30 min)','Nautique',53.36,'Combo jet ski 15 min + bouée tractée 15 min. Départ plage de Saly. Équipements de sécurité fournis.',null,'Casa Loisirs Saly',true,'{"category": "Nautique", "price_per_day": 35000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Casa Loisirs Saly", "contact_phone": "+221 77 910 10 45"}'::jsonb,false,null),
('Sortie en pirogue (balade 2h)','Nautique',30.49,'Balade en pirogue traditionnelle sur l''Atlantique. Observation des dauphins possible. Guide inclus.',null,'Saly Aventure',true,'{"category": "Nautique", "price_per_day": 20000, "price_per_week": null, "deposit_fcfa": null, "min_days": 1, "condition": "Bon état", "region": "Thiès", "annonceur": "Saly Aventure", "contact_phone": "Voir site"}'::jsonb,false,null),
('Jet ski Dakar plage Ngor (session)','Nautique',38.11,'Session jet ski sur la plage de Ngor. Île de Ngor visible. Instructeur présent.',null,'Monaco Beach Boby Jet Ski',true,'{"category": "Nautique", "price_per_day": 25000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Monaco Beach Boby Jet Ski", "contact_phone": "Voir site"}'::jsonb,false,null),
('Stand up paddle (SUP) 1h','Nautique',18.29,'Location paddle stand up sur plage de Saly. Initiation possible. Combinaison anti-UV fournie.',null,'X''Trem Jet Sénégal',true,'{"category": "Nautique", "price_per_day": 12000, "price_per_week": 72000, "deposit_fcfa": 20000, "min_days": 1, "condition": "Bon état", "region": "Thiès", "annonceur": "X''Trem Jet Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Scooter 125cc (journée)','Moto/Scooter',15.24,'Scooter pour découvrir la Petite Côte de manière autonome. Casque inclus. Carburant non inclus.',null,'Ngaparou Aventures',true,'{"category": "Moto/Scooter", "price_per_day": 10000, "price_per_week": 60000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Bon état", "region": "Thiès", "annonceur": "Ngaparou Aventures", "contact_phone": "+221 33 958 53 97"}'::jsonb,false,null),
('Moto trail 250cc (excursion)','Moto/Scooter',38.11,'Moto trail idéale pour excursions en brousse et pistes. Guide et circuit disponibles. Casque inclus.',null,'Moto Découverte Sénégal',true,'{"category": "Moto/Scooter", "price_per_day": 25000, "price_per_week": 150000, "deposit_fcfa": 80000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Moto Découverte Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Moto 125cc (randonnée journée)','Moto/Scooter',22.87,'Location moto journée ou semaine sur Dakar et Petite Côte. Large choix de modèles disponibles.',null,'Location motos et scooters Sénégal',true,'{"category": "Moto/Scooter", "price_per_day": 15000, "price_per_week": 90000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Location motos et scooters Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Vélo VTT (journée ou semaine)','Moto/Scooter',7.62,'VTT pour explorer les pistes et forêts de la Petite Côte. Réparations et assistance incluses.',null,'Ngaparou Aventures',true,'{"category": "Moto/Scooter", "price_per_day": 5000, "price_per_week": 30000, "deposit_fcfa": 10000, "min_days": 1, "condition": "Bon état", "region": "Thiès", "annonceur": "Ngaparou Aventures", "contact_phone": "+221 33 958 53 97"}'::jsonb,false,null),
('Robe de mariée princesse (location)','Mode/Mariage',76.22,'Robe de mariée princesse avec traine. Accompagnement styliste inclus. Ajustements possibles. Dakar.',null,'Just married',true,'{"category": "Mode/Mariage", "price_per_day": 50000, "price_per_week": null, "deposit_fcfa": 100000, "min_days": 1, "condition": "Excellent état", "region": "Dakar", "annonceur": "Just married", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Robe de soirée longue (cérémonie)','Mode/Mariage',30.49,'Robes de soirée et de cocktail pour cérémonies baptêmes anniversaires. Plusieurs modèles disponibles.',null,'La promise Bridal Dakar',true,'{"category": "Mode/Mariage", "price_per_day": 20000, "price_per_week": null, "deposit_fcfa": 30000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "La promise Bridal Dakar", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Costume homme mariage/cérémonie','Mode/Mariage',38.11,'Costume 3 pièces homme pour mariages et cérémonies. Chemise et cravate incluses. Tailles variées.',null,'The Day of Today',true,'{"category": "Mode/Mariage", "price_per_day": 25000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "The Day of Today", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Ensemble wax tenue africaine','Mode/Mariage',22.87,'Tenues africaines wax et bogolan pour cérémonies et événements. Choix de tissus et coupes.',null,'Just married',true,'{"category": "Mode/Mariage", "price_per_day": 15000, "price_per_week": null, "deposit_fcfa": 20000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Just married", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Vidéoprojecteur Full HD + écran 3m','Audiovisuel/IT',38.11,'Vidéoprojecteur Full HD 3000 lumens avec écran 3m. Câbles HDMI inclus. Livraison Dakar.',null,'NERI GROUP',true,'{"category": "Audiovisuel/IT", "price_per_day": 25000, "price_per_week": 150000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "NERI GROUP", "contact_phone": "+221 77 482 59 99"}'::jsonb,false,null),
('Lot 10 PC portables (séminaire)','Audiovisuel/IT',121.96,'10 ordinateurs portables avec logiciels bureautiques. Idéal formations et séminaires. Livraison incluse.',null,'Mondial Business Mobus',true,'{"category": "Audiovisuel/IT", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 150000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Mondial Business Mobus", "contact_phone": "+221 77 627 09 09"}'::jsonb,false,null),
('Système micro-conférence (salle 50p)','Audiovisuel/IT',45.73,'Système de sonorisation pour conférence : micro sans fil podium écran. Technicien disponible.',null,'Mondial Business Mobus',true,'{"category": "Audiovisuel/IT", "price_per_day": 30000, "price_per_week": 180000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Mondial Business Mobus", "contact_phone": "+221 77 627 09 09"}'::jsonb,false,null),
('Borne selfie photobooth animé','Audiovisuel/IT',121.96,'Borne selfie avec fond personnalisable et impression photo instantanée. Idéal mariages soirées.',null,'Dakar Vidéo projecteur location service',true,'{"category": "Audiovisuel/IT", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 150000, "min_days": 1, "condition": "Excellent état", "region": "Dakar", "annonceur": "Dakar Vidéo projecteur location service", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Salle de réunion 20 personnes (journée)','Espace/Bureau',76.22,'Salle climatisée avec projecteur WiFi tableau blanc. Café et eau inclus. Dieuppeul II.',null,'DAKAR Coworking',true,'{"category": "Espace/Bureau", "price_per_day": 50000, "price_per_week": 300000, "deposit_fcfa": 0, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "DAKAR Coworking", "contact_phone": "+221 77 332 81 87"}'::jsonb,false,null),
('Bureau privé (journée coworking)','Espace/Bureau',38.11,'Bureau privé dans espace coworking sécurisé 24/7. Imprimante scanner WiFi inclus. Sud Foire.',null,'Freepenseur',true,'{"category": "Espace/Bureau", "price_per_day": 25000, "price_per_week": 150000, "deposit_fcfa": 0, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Freepenseur", "contact_phone": "Voir site"}'::jsonb,false,null),
('Espace événementiel 100 personnes','Espace/Bureau',228.67,'Salle modulable pour 100 personnes. Scène sonorisation tables et chaises. Parking disponible.',null,'Dakar CoWorking',true,'{"category": "Espace/Bureau", "price_per_day": 150000, "price_per_week": 900000, "deposit_fcfa": 300000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Dakar CoWorking", "contact_phone": "Voir site"}'::jsonb,false,null),
('Bâche PVC imprimée 6×4m','Bâche/Structure',22.87,'Bâche publicitaire ou décorative PVC. Fabrication possible sous 48h. Pose sur structure incluse.',null,'Africa Bâches',true,'{"category": "Bâche/Structure", "price_per_day": 15000, "price_per_week": 90000, "deposit_fcfa": 30000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Africa Bâches", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Structure gonflable stand/arcade','Bâche/Structure',68.6,'Structure gonflable (arc de triomphe stand entrée) pour événements et promotions. Gonfleur inclus.',null,'TOUBA BACHE du Sénégal',true,'{"category": "Bâche/Structure", "price_per_day": 45000, "price_per_week": 270000, "deposit_fcfa": 80000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "TOUBA BACHE du Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Food truck équipé (cuisine mobile)','Food truck',228.67,'Food truck entièrement équipé : cuisine plancha friteuse réfrigérateur. Idéal animations et festivals.',null,'Nomad Foodtruck Sénégal',true,'{"category": "Food truck", "price_per_day": 150000, "price_per_week": 900000, "deposit_fcfa": 300000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Nomad Foodtruck Sénégal", "contact_phone": "Voir Facebook"}'::jsonb,false,null),
('Quad Polaris (session 1h brousse)','Quad/Aventure',38.11,'Session quad 1h sur pistes et forêts autour de Saly. Casque et équipements fournis. Instructeur présent.',null,'AFRICA Raids',true,'{"category": "Quad/Aventure", "price_per_day": 25000, "price_per_week": null, "deposit_fcfa": 30000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "AFRICA Raids", "contact_phone": "+221 33 954 97 22"}'::jsonb,false,null),
('Buggy biplace (demi-journée 3h)','Quad/Aventure',68.6,'Buggy biplace avec guide pour 3h d''excursion villages et brousse autour de Saly. Eau et snack inclus.',null,'Pape Loisirs',true,'{"category": "Quad/Aventure", "price_per_day": 45000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Pape Loisirs", "contact_phone": "Voir site"}'::jsonb,false,null),
('Combo quad + buggy (excursion 3h)','Quad/Aventure',99.09,'Formule combinée : 1h30 quad + 1h30 buggy. Découverte villages sénégalais et pistes forestières.',null,'Saly Loisirs',true,'{"category": "Quad/Aventure", "price_per_day": 65000, "price_per_week": null, "deposit_fcfa": 80000, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Saly Loisirs", "contact_phone": "Voir site"}'::jsonb,false,null),
('Quad 90cc enfant (session accompagnée)','Quad/Aventure',18.29,'Quad homologué dès 7 ans. Guide accompagnateur dédié. Parcours adapté sécurisé. Casque obligatoire fourni.',null,'Easy Quad Saly',true,'{"category": "Quad/Aventure", "price_per_day": 12000, "price_per_week": null, "deposit_fcfa": 20000, "min_days": 1, "condition": "Bon état", "region": "Thiès", "annonceur": "Easy Quad Saly", "contact_phone": "Voir site"}'::jsonb,false,null),
('Go-kart adulte (session 10 min)','Karting',22.87,'Circuit extérieur 9km face station API Ngaparou. Kart 200cc adultes dès 15 ans. Chrono et bar sur place.',null,'KART''ing Saly',true,'{"category": "Karting", "price_per_day": 15000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Excellent état", "region": "Thiès", "annonceur": "KART''ing Saly", "contact_phone": "+221 33 958 50 02"}'::jsonb,false,null),
('Go-kart enfant (session 7 min)','Karting',12.2,'Kart junior dès 7 ans. Circuit sécurisé adapté. Formule anniversaire groupe disponible. Bar sur place.',null,'KART''ing Saly',true,'{"category": "Karting", "price_per_day": 8000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Excellent état", "region": "Thiès", "annonceur": "KART''ing Saly", "contact_phone": "+221 33 958 50 02"}'::jsonb,false,null),
('Cours de kitesurf (2h avec instructeur)','Sport nautique',76.22,'Cours initiation ou perfectionnement kitesurf à Saly. Matériel complet fourni (aile bar planche). Moniteur certifié.',null,'DaKite Sénégal',true,'{"category": "Sport nautique", "price_per_day": 50000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "DaKite Sénégal", "contact_phone": "Voir site"}'::jsonb,false,null),
('Kayak mer (demi-journée 4h)','Sport nautique',22.87,'Kayak mono ou biplace sur la Corniche dakaroise. Sortie guidée atolls et Anse Bernard. Gilet inclus.',null,'Oceanium de Dakar',true,'{"category": "Sport nautique", "price_per_day": 15000, "price_per_week": 72000, "deposit_fcfa": 10000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Oceanium de Dakar", "contact_phone": "Voir site"}'::jsonb,false,null),
('Leçon de surf (1h30 avec moniteur)','Sport nautique',30.49,'Cours de surf à la plage de Yoff. Moniteur qualifié. Planche et leash fournis. Dès 10 ans. Niveaux débutants bienvenus.',null,'Malika Surf Camp',true,'{"category": "Sport nautique", "price_per_day": 20000, "price_per_week": null, "deposit_fcfa": 10000, "min_days": 1, "condition": "Bon état", "region": "Dakar", "annonceur": "Malika Surf Camp", "contact_phone": "Voir site"}'::jsonb,false,null),
('Sortie pêche sportive (journée 8h)','Pêche/Bateau',228.67,'Bateau de pêche sportive pour 4-6 personnes. Appâts et matériel inclus. Capitaine expérimenté. Départ plage Saly.',null,'Saly Aventure',true,'{"category": "Pêche/Bateau", "price_per_day": 150000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Très bon état", "region": "Thiès", "annonceur": "Saly Aventure", "contact_phone": "Voir site"}'::jsonb,false,null),
('Voilier charter (journée avec skipper)','Pêche/Bateau',381.12,'Voilier privatisé avec skipper professionnel. Sortie coucher de soleil ou journée complète. Boissons incluses.',null,'Terrou-Bi',true,'{"category": "Pêche/Bateau", "price_per_day": 250000, "price_per_week": null, "deposit_fcfa": 100000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Terrou-Bi", "contact_phone": "Voir site"}'::jsonb,false,null),
('Château gonflable (journée)','Animation enfants',121.96,'Château gonflable grande taille. Livraison montage et démontage inclus. Idéal anniversaires et kermesses.',null,'Kid''Air',true,'{"category": "Animation enfants", "price_per_day": 80000, "price_per_week": 480000, "deposit_fcfa": 100000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "Kid''Air", "contact_phone": "Voir site"}'::jsonb,false,null),
('Mascotte personnage déguisé (2h)','Animation enfants',60.98,'Mascotte au choix (Mickey Spiderman Super Mario Unicorn Clown). Animation spectacle enfants 2h. Dakar et banlieue.',null,'King Mascotte',true,'{"category": "Animation enfants", "price_per_day": 40000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Excellent état", "region": "Dakar", "annonceur": "King Mascotte", "contact_phone": "+221 77 350 84 37"}'::jsonb,false,null),
('Animation clown/magie/acrobate (2h)','Animation enfants',91.47,'Clown magicien acrobate ou jongleur pour anniversaires fêtes scolaires. 1 Avenue Malick Sy Dakar.',null,'FUN CITY Dakar',true,'{"category": "Animation enfants", "price_per_day": 60000, "price_per_week": null, "deposit_fcfa": 0, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "FUN CITY Dakar", "contact_phone": "Voir site"}'::jsonb,false,null),
('Machine pop-corn + barbe à papa (journée)','Animation enfants',53.36,'Duo machine pop-corn + barbe à papa. Livraison et reprise incluses à Dakar. Ingrédients pour 200 portions.',null,'King Mascotte',true,'{"category": "Animation enfants", "price_per_day": 35000, "price_per_week": 210000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "King Mascotte", "contact_phone": "+221 77 350 84 37"}'::jsonb,false,null),
('Jacuzzi gonflable à domicile (soirée 4h)','Bien-être',114.34,'Spa gonflable installé chez vous pour la soirée. 4-6 personnes. Livraison installation dépose incluses. Dakar + banlieue.',null,'Fun Spa Dakar',true,'{"category": "Bien-être", "price_per_day": 75000, "price_per_week": null, "deposit_fcfa": 50000, "min_days": 1, "condition": "Excellent état", "region": "Dakar", "annonceur": "Fun Spa Dakar", "contact_phone": "Voir site"}'::jsonb,false,null),
('Spa privé journée (installation à domicile)','Bien-être',76.22,'Spa privatif livré et installé. Option massage à domicile disponible. Bonne ambiance garantie. Dakar.',null,'VIP Spa Jacuzzi Massage',true,'{"category": "Bien-être", "price_per_day": 50000, "price_per_week": 300000, "deposit_fcfa": 50000, "min_days": 1, "condition": "Très bon état", "region": "Dakar", "annonceur": "VIP Spa Jacuzzi Massage", "contact_phone": "Voir Facebook"}'::jsonb,false,null);

-- Attribution a l'admin (le plus ancien si plusieurs).
with adm as (select id from public.profiles where role='admin' order by created_at asc limit 1)
insert into public.products(name,category,price,stock,description,image_url,vendor_id,vendor_name,active,is_rental,rental_specs,is_realestate,realestate_specs)
select an.name,an.category,an.price_eur,1,an.description,an.image_url,(select id from adm),an.vendor_name,true,an.is_rental,an.rental_specs,an.is_realestate,an.realestate_specs
  from _annonces an
 where not exists (select 1 from public.products p where p.vendor_id=(select id from adm) and p.name=an.name
     and coalesce(p.is_rental,false)=an.is_rental and coalesce(p.is_realestate,false)=an.is_realestate);

-- Recap.
select 'immobilier' as module, count(*) as annonces from _annonces where is_realestate
 union all select 'location', count(*) from _annonces where is_rental;
