-- ============================================================================
-- Prospection 2e lot (2026-08-27) : nouvelles annonces Immobilier (appartements/
-- villas/terrains à louer ou à vendre — PAS des agences) + nouveaux articles
-- Location matériel, sourcés via recherche web (Expat-Dakar, CoinAfrique,
-- recherche site:facebook.com/site:instagram.com), dédupliqués contre
-- prospection/catalogue_immobilier_senegal.csv et catalogue_location_senegal.csv.
-- Même structure que sql/2026_08_12_catalogue_annonces.sql. Idempotent.
--
-- 22/25 annonces Immobilier importées (3 sans prix vérifiable exclues : Villa 8
-- pièces Saly, Terrain 300m² Saly Carrefour, Appartement meublé Liberté 6 Ext. —
-- restent dans le CSV prospection pour relance manuelle, pas de prix inventé).
-- 16/16 articles Location importés ; 10 sans prix ferme passés en "vitrine"
-- (is_vitrine:true dans rental_specs, prix placeholder 1.00€ jamais affiché —
-- même mécanisme que sql/2026_08_12_loueurs_vitrine.sql, PriceDisplay/
-- isVitrineListing affichent "Sur devis").
-- ============================================================================

do $$ begin
  if not exists (select 1 from public.profiles where role='admin') then
    raise exception 'Aucun compte admin (profiles.role=admin) — impossible d''attribuer les annonces.';
  end if;
end $$;

drop table if exists _annonces_b2;
create temp table _annonces_b2(name text, category text, price_eur numeric, description text, image_url text, vendor_name text, is_rental bool, rental_specs jsonb, is_realestate bool, realestate_specs jsonb);
insert into _annonces_b2 values
('Appartement F4 Sicap Liberté 1 (nouveau)','Immobilier',1295.82,'Appartement 3 chambres à louer, Sicap Liberté 1.',null,'Habiter.biz',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":850000,"surface_m2":null,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Sicap Liberté 1","annonceur":"Habiter.biz","contact_phone":"+221 77 284 78 78"}'::jsonb),
('Appartement vue mer Mermoz (nouveau)','Immobilier',1829.39,'Appartement 3 chambres vue océan, Mermoz.',null,'Habiter.biz',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":1200000,"surface_m2":null,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Mermoz","annonceur":"Habiter.biz","contact_phone":"+221 77 284 78 78"}'::jsonb),
('Appartement F3 Mamelles','Immobilier',586.93,'Appartement 3 chambres, Mamelles.',null,'Habiter.biz',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":385000,"surface_m2":null,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Mamelles","annonceur":"Habiter.biz","contact_phone":"+221 77 284 78 78"}'::jsonb),
('Appartement F2 Mermoz Batrain','Immobilier',571.68,'Appartement 2 chambres, Mermoz Batrain.',null,'Particulier',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":375000,"surface_m2":null,"rooms":null,"bedrooms":2,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Mermoz","annonceur":"Particulier","contact_phone":"+221 76 775 39 11"}'::jsonb),
('Appartement F3 Liberté 5','Immobilier',1067.14,'Appartement non meublé, 180m², Liberté 5.',null,'Particulier',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":700000,"surface_m2":180,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":false,"region":"Dakar","location_label":"Liberté 5","annonceur":"Particulier","contact_phone":"+221 77 193 09 09"}'::jsonb),
('Appartement F2 Hann Maristes','Immobilier',457.35,'Appartement 2 chambres, 100m², Hann Maristes.',null,'Particulier',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":300000,"surface_m2":100,"rooms":null,"bedrooms":2,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Hann Maristes","annonceur":"Particulier","contact_phone":"+221 77 126 78 78"}'::jsonb),
('Appartement F2 Sicap Liberté VDN','Immobilier',533.57,'Appartement 2 chambres, 90m², proche VDN.',null,'Particulier',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":350000,"surface_m2":90,"rooms":null,"bedrooms":2,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Sicap Liberté / VDN","annonceur":"Particulier","contact_phone":"+221 77 559 43 78"}'::jsonb),
('Appartement F3 Almadies (nouveau)','Immobilier',914.69,'Appartement 3 chambres, 200m², Almadies.',null,'Kamaisha Group',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":600000,"surface_m2":200,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Almadies","annonceur":"Kamaisha Group","contact_phone":null}'::jsonb),
('Duplex F3 Ngor Almadies','Immobilier',2591.63,'Duplex non meublé, Ngor Almadies.',null,'Habiter.biz',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":1700000,"surface_m2":null,"rooms":null,"bedrooms":3,"bathrooms":null,"furnished":false,"region":"Dakar","location_label":"Ngor / Almadies","annonceur":"Habiter.biz","contact_phone":null}'::jsonb),
('Penthouse F4 Le Plateau','Immobilier',2439.18,'Penthouse 4 chambres, 218m², Plateau.',null,'Particulier',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":1600000,"surface_m2":218,"rooms":null,"bedrooms":4,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Plateau","annonceur":"Particulier","contact_phone":"+221 78 653 73 73"}'::jsonb),
('Appartement F4 Point E (vente)','Immobilier',274408.23,'Appartement 4 pièces à vendre, Point E.',null,'Agence pro',false,null,true,'{"transaction":"vente","property_type":"appartement","price_fcfa":180000000,"surface_m2":null,"rooms":4,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Point E","annonceur":"Agence pro","contact_phone":null}'::jsonb),
('Appartement F3 Dakar Plateau (nouveau)','Immobilier',426.86,'Appartement F3 à louer, Dakar Plateau.',null,'Agence pro',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":280000,"surface_m2":null,"rooms":3,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Plateau","annonceur":"Agence pro","contact_phone":null}'::jsonb),
('Appartement Almadies (vente)','Immobilier',27440.82,'Appartement à vendre, Almadies.',null,'Agence pro',false,null,true,'{"transaction":"vente","property_type":"appartement","price_fcfa":18000000,"surface_m2":null,"rooms":null,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Almadies","annonceur":"Agence pro","contact_phone":null}'::jsonb),
('Appartement F3 Hann Bel-Air','Immobilier',686.02,'Appartement F3 à louer, Hann Bel-Air.',null,'Agence pro',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":450000,"surface_m2":null,"rooms":3,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Hann Bel-Air","annonceur":"Agence pro","contact_phone":null}'::jsonb),
('Appartement F4 Ngor (vente)','Immobilier',304898.03,'Appartement 4 pièces à vendre, Ngor.',null,'Agence pro',false,null,true,'{"transaction":"vente","property_type":"appartement","price_fcfa":200000000,"surface_m2":null,"rooms":4,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Dakar","location_label":"Ngor","annonceur":"Agence pro","contact_phone":null}'::jsonb),
('Grand terrain Cap Skirring 16000m²','Immobilier',804930.81,'Grand terrain (réf. 5077_GL), Cap Skirring.',null,'Particulier',false,null,true,'{"transaction":"vente","property_type":"terrain","price_fcfa":528000000,"surface_m2":16000,"rooms":null,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Ziguinchor","location_label":"Cap Skirring","annonceur":"Particulier","contact_phone":"+221 78 138 59 59"}'::jsonb),
('Terrain Cap Skirring 800m²','Immobilier',53357.16,'Terrain 800m² à vendre, Cap Skirring.',null,'Particulier',false,null,true,'{"transaction":"vente","property_type":"terrain","price_fcfa":35000000,"surface_m2":800,"rooms":null,"bedrooms":null,"bathrooms":null,"furnished":null,"region":"Ziguinchor","location_label":"Cap Skirring","annonceur":"Particulier","contact_phone":"+221 77 126 78 78"}'::jsonb),
('Maison 5 chambres Kahone','Immobilier',18293.88,'Maison 5 chambres, 600m², Kahone.',null,'Particulier',false,null,true,'{"transaction":"vente","property_type":"villa","price_fcfa":12000000,"surface_m2":600,"rooms":null,"bedrooms":5,"bathrooms":null,"furnished":null,"region":"Kaolack","location_label":"Kahone","annonceur":"Particulier","contact_phone":"+221 78 585 08 68"}'::jsonb),
('Maison 6 chambres Kaolack','Immobilier',22867.35,'Maison 6 chambres, 200m², Kaolack.',null,'Particulier',false,null,true,'{"transaction":"vente","property_type":"villa","price_fcfa":15000000,"surface_m2":200,"rooms":null,"bedrooms":6,"bathrooms":null,"furnished":null,"region":"Kaolack","location_label":"Kaolack ville","annonceur":"Particulier","contact_phone":"+221 76 767 67 50"}'::jsonb),
('Bureau 90m² Rue Félix Faure Plateau','Immobilier',2286.74,'Local commercial haute visibilité, 2 niveaux, sécurité 24/7.',null,'Alpha',false,null,true,'{"transaction":"location","property_type":"bureau","price_fcfa":1500000,"surface_m2":90,"rooms":null,"bedrooms":null,"bathrooms":null,"furnished":false,"region":"Dakar","location_label":"Plateau (Rue Félix Faure)","annonceur":"Alpha","contact_phone":"+221 78 733 21 35"}'::jsonb),
('Appartement F2 Touba Khaïra','Immobilier',228.67,'2 chambres salon, usage bureautique, 2e étage.',null,'2SMS Immobilier SARL',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":150000,"surface_m2":null,"rooms":null,"bedrooms":2,"bathrooms":null,"furnished":null,"region":"Diourbel","location_label":"Touba Khaïra","annonceur":"2SMS Immobilier SARL","contact_phone":"+221 78 138 79 80"}'::jsonb),
('Studio meublé Mbour Nanning','Immobilier',137.2,'Studio meublé, piscine, résidence sécurisée.',null,'Jean-Damien Colin',false,null,true,'{"transaction":"location","property_type":"appartement","price_fcfa":90000,"surface_m2":43,"rooms":null,"bedrooms":1,"bathrooms":null,"furnished":true,"region":"Thiès","location_label":"Mbour (route Joal)","annonceur":"Jean-Damien Colin","contact_phone":"+221 77 840 94 72"}'::jsonb),
('Kia Optima automatique climatisée','Voiture',45.73,'Automatique, clim, Bluetooth, papiers en règle. 35 000 F/j hors Dakar.',null,'Malickia Business',true,'{"category":"Voiture","price_per_day":30000,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":"Bon état","region":"Dakar","annonceur":"Malickia Business","contact_phone":"+221 77 335 58 51"}'::jsonb,false,null),
('Groupe électrogène — location Dakar','BTP/Énergie',1,'Page dédiée location de groupes électrogènes à Dakar.',null,'Location Groupe Électrogène',true,'{"category":"BTP/Énergie","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Location Groupe Électrogène","contact_phone":"+221 78 445 15 16","is_vitrine":true}'::jsonb,false,null),
('Groupe électrogène 33 KVA','BTP/Énergie',1,'Location groupe électrogène 33 KVA, livraison tout le Sénégal.',null,'Diallo BTP Logistique',true,'{"category":"BTP/Énergie","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Diallo BTP Logistique","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('Groupe électrogène (Kobe BTP)','BTP/Énergie',1,'Location de groupes électrogènes, devis jour/semaine/mois.',null,'Kobe BTP Sénégal',true,'{"category":"BTP/Énergie","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Kobe BTP Sénégal","contact_phone":"+221 77 608 18 63","is_vitrine":true}'::jsonb,false,null),
('Pack mobilier + chapiteaux + sono événementiel','Événementiel',1,'Tentes Garden, chapiteaux transparents, igloos 100-1350m², éclairage/sono.',null,'Ayuf Holding SN',true,'{"category":"Événementiel","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Ayuf Holding SN","contact_phone":"+221 71 057 03 00","is_vitrine":true}'::jsonb,false,null),
('Chaises Napoléon transparentes','Événementiel',3.05,'Chaises Napoléon transparentes, 2 000 F/chaise.',null,'Particulier',true,'{"category":"Événementiel","price_per_day":2000,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null}'::jsonb,false,null),
('Chaises VIP (location, dès 30)','Événementiel',1.22,'Chaises VIP à partir de 800 F/jour (minimum 30 chaises).',null,'Particulier',true,'{"category":"Événementiel","price_per_day":800,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null}'::jsonb,false,null),
('Pack bâche + sono + chaises VIP + tapis rouge + podium','Événementiel',1,'Pack complet : bâche, sonorisation, chaises VIP, tapis rouge, podium.',null,'Particulier',true,'{"category":"Événementiel","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('Table ronde (location)','Événementiel',15.24,'Table ronde 12 personnes, 10 000 F.',null,'Particulier',true,'{"category":"Événementiel","price_per_day":10000,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null}'::jsonb,false,null),
('Robe de mariée / cérémonie sur mesure','Mode/Mariage',1,'Robes de mariée prêt-à-porter ou sur mesure, livraison possible.',null,'Particulier',true,'{"category":"Mode/Mariage","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('Robe de soirée / cérémonie (divers modèles)','Mode/Mariage',1,'Location robes soirée, mariage, wax.',null,'Particulier (@soluchic_221)',true,'{"category":"Mode/Mariage","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier (@soluchic_221)","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('Location voiture — Autowou (plateforme)','Voiture',1,'Plateforme locale de location de voiture sans chauffeur, dès ≈15 700 F/j.',null,'Autowou',true,'{"category":"Voiture","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Autowou","contact_phone":"+221 77 382 31 83","is_vitrine":true}'::jsonb,false,null),
('Scooter (location Pikine/Mariste)','Moto/Scooter',4.57,'Scooters en location, prix attractifs.',null,'Particulier',true,'{"category":"Moto/Scooter","price_per_day":3000,"price_per_week":20000,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null}'::jsonb,false,null),
('Motos & scooters (particuliers)','Moto/Scooter',1,'Négociation directe entre particuliers, plusieurs annonces motos.',null,'Groupe FB « Location motos et scooters Sénégal »',true,'{"category":"Moto/Scooter","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Groupe FB « Location motos et scooters Sénégal »","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('4x4 (location, Diallo BTP)','Voiture',1,'Location de 4x4, livraison partout au Sénégal.',null,'Diallo BTP Logistique',true,'{"category":"Voiture","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Diallo BTP Logistique","contact_phone":null,"is_vitrine":true}'::jsonb,false,null),
('Matériel événementiel (pack complet)','Événementiel',1,'Location de matériel pour événements (annonce générique).',null,'Particulier',true,'{"category":"Événementiel","price_per_day":null,"price_per_week":null,"deposit_fcfa":null,"min_days":1,"condition":null,"region":"Dakar","annonceur":"Particulier","contact_phone":null,"is_vitrine":true}'::jsonb,false,null);

with adm as (select id from public.profiles where role='admin' order by created_at asc limit 1)
insert into public.products(name,category,price,stock,description,image_url,vendor_id,vendor_name,active,is_rental,rental_specs,is_realestate,realestate_specs)
select an.name,an.category,an.price_eur,1,an.description,an.image_url,(select id from adm),an.vendor_name,true,an.is_rental,an.rental_specs,an.is_realestate,an.realestate_specs
  from _annonces_b2 an
 where not exists (select 1 from public.products p where p.vendor_id=(select id from adm) and p.name=an.name
     and coalesce(p.is_rental,false)=an.is_rental and coalesce(p.is_realestate,false)=an.is_realestate);

select 'immobilier' as module, count(*) as annonces from _annonces_b2 where is_realestate
 union all select 'location', count(*) from _annonces_b2 where is_rental;
