-- 2026-08-31 — Import des lignes de bus urbains Dakar Dem Dikk (DDD),
-- extraites depuis https://demdikk.sn/reseau-urbain-dakar/ (section "LIGNES
-- URBAINES" uniquement — 17 lignes (dont 2 boucles 502/503 et 2 lignes "TAF
-- TAF" sans numéro classique), itinéraire rue par rue dans `escales`,
-- pas de coordonnées GPS/prix/horaires publiés par la source). Même
-- convention que l'import AFTU (sql/2026_08_31_aftu_tata_lines_import.sql) :
-- table transport_lines déjà existante, aucune migration de schéma.
-- Lignes 502/503 sont des boucles (même terminus départ/arrivée).
insert into public.transport_lines
  (operator, vehicle_type, origin_city, origin_gare, arrival_gare, destinations, destination_main, escales, source, collected_at, active)
values
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Parcelles Assainies', 'Leclerc', 'Ligne 1 : Parcelles Assainies → Leclerc', 'Leclerc', 'Terminus Parcelles Assainies|Sapeur Pompiers|Unités 09 10 15|Ecole Dior|Terrain Acapes|Unités 22 24|Marché Grand Médine|Rond point 26|VDN-Foire|Cité Keur Gorgui|Ecole Normale|Ucad|Rond point Sham|Marché Tilène|Poste Médina|Difoncé|Sandaga|Avenue George Pompidou|Place de l''Indépendance|Gare TER|Embarcadère|Terminus Leclerc', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Liberté 5 (Dieuppeul)', 'Leclerc', 'Ligne 4 : Liberté 5 (Dieuppeul) → Leclerc', 'Leclerc', 'Terminus Liberté 5 (Dieuppeul)|Cité Derklé|Rond point Liberté 6|Khar Yalla|Cité Marine|CEM Dieuppeul 3|Eglise Martyrs de l''ouganda|SDE|Collège Sacré Cœur|Sicap Karack|Point E|Université Amphate BA|Canal 4|Marché Fass|Gueule Tapée|Rond Point Sham|Marché Tilène|Poste Médina|Difoncé|Sandaga|ASECNA|Boulevard de la République|Avenue Léopold Sédar Senghor|Place de l''Indépendance|Gare TER|Embarcadère|Terminus Leclerc', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Ouakam', 'Palais 2', 'Ligne 7 : Ouakam → Palais 2', 'Palais 2', 'Terminus Ouakam|Cité Assemblée|Cité Comico|Sortie Ouakam|Hopital IHO|Mermoz|ENEA|Ecole Normale|UCAD|Rond point Sham|Marché Tilen|Poste Médina|Difoncé|Sandaga|Avenue George Pompidou|Place de l''Indépendance|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point assemblée nationale|Institut pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Aéroport LSS', 'Palais 2', 'Ligne 8 : Aéroport LSS → Palais 2', 'Palais 2', 'Terminus Aéroport LSS|Cité Asecna|Yoff Village|Pond Foire|Stade Léopold Sédar Senghor|Patte d''Oie|Grand Yoff|Hopital Général Idrissa Pouye (Ex CTO)|Cité des Eaux|Station Castor|Avenue Bourguiba|Jet d''eau|Stade demba Diop|Dial Diop (ex rue 10)|Zone B|Point E|UCAD|Rond point Sham|Marché Tilen|Poste Médina|Difoncé|Sandaga|ASECNA|Bld de la République|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point Assemblée Nationale|Institut Pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Liberté 6', 'Palais 2', 'Ligne 9 : Liberté 6 → Palais 2', 'Palais 2', 'Terminus Liberté 6|Rond Point JVC|Sacré Cœur|IPG|Terminus Dieuppeul|Allées Ababacar Sy|Rond Point Jet d''Eau|Niary Tally|Eglise Sainte Thérèse|Lycée Blaise Diagne|Lycée Kenedy|Obelisque|Centenaire|Rond point RTS|Poste Médina|Difoncé|Sandaga|Avenue George Pompidou|Place de l''Indépendance|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point assemblée nationale|Institut pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'liberté 5 (Dieuppeul)', 'Palais 2', 'Ligne 10 : liberté 5 (Dieuppeul) → Palais 2', 'Palais 2', 'Terminus liberté 5 (Dieuppeul)|Cité Derklé|Rond point Liberté 6|Khar Yalla|Cité Marine|CEM Ousmane Socé Diop|Eglise Martyrs de l''Ouganda|SDE|Dakar sacré coeur|Stade Demba Diop|Avenue Bourguiba|Ecole Normale|Poste Fann|Rue Aimé césaire|Ministère de la Santé|Corniche Ouest|IFAN|Hotel Terrou|Tunnel de soumbédioune|Village Artisanal de Soumbédioune|Prison Rebeus|Turbinal de dakar|Boulevard de la République|Sorano|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point assemblée nationale|Institut Pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'liberté 5 (Dieuppeul)', 'Palais 2', 'Ligne 13 : liberté 5 (Dieuppeul) → Palais 2', 'Palais 2', 'Terminus liberté 5 (Dieuppeul)|Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)|Station Castors|Marché HLM|Ouagou Niayes|BOP|Masalikul Djinane|CSS|Lycée Kennedy|Boulevard Général De Gaule|Centenaire|RTS|Grande mosquée|Allées Papa Guèye Fall|Petersen|Avenue Faidherbe|Esso Port|Gare de Dakar|Place de l''Indépendance|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point assemblée nationale|Institut pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Liberté 5 (Dieuppeul)', 'Liberté 5 (Dieuppeul)', 'Ligne 18 : Liberté 5 (Dieuppeul) → Liberté 5 (Dieuppeul)', 'Liberté 5 (Dieuppeul)', 'Terminus Liberté 5 (Dieuppeul)|Cité Derklé|Rond Point Liberté 6|Khar Yalla|Cité Marine|Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)|Station Castors|Marché HLM|Ouagou Niayes|BOP|Masalikul Djinane|CSS|Colobane|Service des mines|Place BAKOU|Police Bel Air|Grand Moulin de Dakar|Bel Air|Arsanel|Gare de dakar|Esso Port|Place de l''Indépendance|Avenue Georges Pompidou|Rond point Sandaga|Avenue André Peytavin|Lat Dior|Route de la Corniche|Reubeuss|Mosquée Seydou Nourrou Tall|DAF|Rue 6|Médina|Gueule Tapée|Lycée Delafosse|Canal 4|Rond point Sham|Avenue Cheikh Anta Diop|Ecole Normale Supérieure|Avenue Bourguiba|Stade Demba DIOP|Rond Point Jet d''eau|Allées Ababacar Sy|Terminus Liberté 5 (Dieuppeul)', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Dieuppeul', 'Dieuppeul', 'Ligne 20 : Dieuppeul → Dieuppeul', 'Dieuppeul', 'Terminus Dieuppeul|Allées Ababacar Sy|Jet d''Eau|Avenue Bourguiba|Stade Demba Diop|Ecole Normale|Poste Fann|Avenue Cheikh Anta Diop|UCAD|Canal 4|Lycée Delafosse|Gueule Tapée|Rue 6|Médina|DAF|Mosquée seydou Nourrou Tall|Reubeuss|Lat Dior|Avenue Peytavin|Rond point Sandaga|Avenue Gorges Pompidou|Place de l''Indépendance|Gare Ter|Esso Port|Boulevard de l''Arsenal|Central Bel Air (MTOA)|Grands Moulin de Dakar|Police Bel Air|Service des Mines|Colobane|CSS|Masalikul Djinane|Cité Port|Ouagou niayes|Marché HLM|Station Castors|Avenue Cheikh Ahmadou Bamba|Cité Marine|Khar Yalla|Rond Point LIBERTE6|Cité Derklé|Terminus Dieuppeul', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Parcelles', 'Palais 2', 'Ligne 23 : Parcelles → Palais 2', 'Palais 2', 'Terminus des Parcelles|Ecole Dior|Diamalaye|Hlm Grand Médine|Dior|Acapes|Dispensaire Norade|Hopital Mame Abdou|Eglise|Unité 11|Croisement 22|Police Parcelles|Pont Emergent|Ecole Hyacinthe Thiandoum|Rond point Liberté 6|Khar Yalla|Front de Terre|Cité des Eaux|Station castor|Avenue Bourguiba|Stade Demba Diop|Ecole Normale|Poste Fann|Avenue Cheikh Anta Diop|UCAD|Rond Point Sahm|Canal 4|Gueule Tapée|Rue 6|DAF|Poste Médina|Difoncé|Sandaga|ASECNA|Bld de la République|Avenue Léopold Sédar Senghor|Hopitale Principale|Rond point assemblée nationale|Institut Pasteur|Terminus Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Scat Urban', 'Leclerc', 'Ligne 121 : Scat Urban → Leclerc', 'Leclerc', 'Terminus Scat Urban|Mairie Grand Yoff|Pentola|Les deux voies de Sipres|Camp penal|Les deux voies de Liberté 6|Rond point JVC|Boulangerie Zone|Collège Sacré Cœur|Scor liberté|Sicap rue 10|Lycée Blaise Diagne|Place ONU|Canal 4|HLM Fass|Travaux communaux|Rue 22 prolongée|RTS|Allées Papa Guèye Fall|Petersen|Avenue Faidherbe|Place de l''indépendance|Albert Sarraut|BCEAO|Terminus Leclerc', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'liberté 6', 'Ouakam', 'Ligne 319 : liberté 6 → Ouakam', 'Ouakam', 'Terminus liberté 6|Rond Point Liberté 6|Deux voies liberté 6|Rond point JVC|Boulangerie Jaune|Immeuble Mariama|Rond point Cheikh Bethio|Ancien Piste|IHO|Entrée ouakam|Pharmacie cité Aviaon|Pharmacie Mame Seynabou|Case des tous petit|Station shell|Lycée d''excellence privée|Boulangerie N''wely|Terminus Ouakam', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Ouakam', 'Palais 2', 'Ligne TAF TAF OUAKAM (TO1) : Ouakam → Palais 2', 'Palais 2', 'Terminus Ouakam|Brioche d''orée Ouakam|Monument de la Renaissance|Corniche ouest|Avenue Peytavin|Avenue Pompidou|Place de l''Indépendance|Avenue Léopold Sédar Senghor|Avenue Nelson Mandela|Palais 2', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Palais 2', 'Leclerc', 'Ligne 501 : Palais 2 → Leclerc', 'Leclerc', 'Terminus Palais 2|Avenue Nelson Mandela|Avenue Léopold Sédar Senghor|Place de l''Indépendance|Esso Port Embarcadère|Terminus Leclerc', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Gare colobane', 'Gare Colobane', 'Ligne 502 : Gare colobane → Gare Colobane', 'Gare Colobane', 'Gare colobane|Maison du partie|Hampathé Ba|UCAD|Lycee De Lafosse|Police 4em|Rond Point Sham|Gare Colobane', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Gare de Colobane', 'Gare de Colobane', 'Ligne 503 : Gare de Colobane → Gare de Colobane', 'Gare de Colobane', 'Gare de Colobane|Rond Point Bel Air|Mole 8|Cité Isra|Zone industrielle|Service des mines|Gare de Colobane', 'demdikk.sn', current_date, true),
  ('Dakar Dem Dikk (DDD)', 'bus', 'Dakar', 'Ouakam', 'AIBD', 'Ligne TAF TAF (AIBD) : Ouakam → AIBD', 'AIBD', 'Terminus Ouakam|Mamelles|Croisement Almadies|Ngor|Yoff|Rte de l''Aéroport|Foire|VDN|Direction Générale DDD|Rond Point JVC|Rond Point Liberté 6|Itinéraire 213|Police Grand Yoff|Pharmacie Patte d''Oie|Autoroute à Péage|Diamniadio|AIBD', 'demdikk.sn', current_date, true)
;
